services:
  client:
    image: ubuntu:latest
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - gateway
      - bind9
    networks:
      dns-network:
        ipv4_address: 192.168.2.10

  bind9:
    depends_on:
      - gateway
    build:
      context: .
      dockerfile: bind9/Dockerfile
    volumes:
      - ./bind9/config:/etc/bind
    environment:
      - BIND9_USER=root
      - TZ=Europe/Jerusalem
    networks:
      inner-network:
        ipv4_address: 192.168.3.30
    privileged: true # Needed for network operations
    cap_add:
      - NET_ADMIN # Required for iptables or routing

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    networks:
      dns-network:
        ipv4_address: 192.168.2.20
      inner-network:
        ipv4_address: 192.168.3.20
    cap_add:
      - NET_ADMIN # Required for iptables or routing
    privileged: true # Needed for network operations

networks:
  dns-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
  inner-network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 192.168.3.0/24
