services:
  bind9:
    container_name: dns-auth-srv
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Jerusalem
    ports:
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
    restart: unless-stopped
